site_name: QR-Control System Docs
theme:
  name: readthedocs
  palette:
    scheme: slate # Темна тема, щоб очі не випали
    primary: indigo

nav:
  - Головна: index.md
  - Архітектура:
      - Вимоги (SSD): architecture/SSD.md
      - Дизайн (SDD): architecture/SDD.md
      - Інфраструктура (ISD): architecture/ISD.md
      - Специфікація API: api.md
  - Розробка:
      - API & UI Огляд: api-overview.md
      - CI/CD Процес: ci-cd-docs.md
  - Якість:
      - Definition of Done: definition-of-done.md
      - Матриця простежуваності: quality/traceability-matrix.md
  - Різне :
      - Онбординг: developer/onboarding.md

plugins:
  - search
  - swagger-ui-tag # Додаємо цей плагін
