site_name: QR-Control System Docs
theme:
  name: material
  palette:
    scheme: slate # Темна тема, щоб очі не випали
    primary: indigo

nav:
  - Головна: index.md
  - Архітектура:
      - Вимоги (SSD): architecture/SSD.md
      - Дизайн (SDD): architecture/SDD.md
      - Інфраструктура (ISD): architecture/ISD.md
  - Для розробників:
      - Онбординг: developer/onboarding.md
  - Якість:
      - Стратегія тестування: quality/test-strategy.md
      - Матриця простежуваності: quality/traceability-matrix.md